### ISSUE TITLE
Error: The creation of a local Business Manager user isn't allowed with the current server settings.

### ISSUE THREAD

**Issue by lornadsilvasonos** [SalesforceCommerceCloud/sfcc-ci#134]
Trying to use the following command to grant access to a user using 

`sfcc-ci user:create --instance my-instance --login "my-user" --user '{"email":"jdoe@email.org", "first_name":"John", "last_name":"Doe", "roles": ["Administrator"]}`

but get error: The creation of a local Business Manager user isn't allowed with the current server settings.

What is going wrong here?

**Comment by tobiaslohr** [comment]
Hi @lornadsilvasonos, user management is supposed to happen through Account Manager nowadays. That being said, the user record you attempt to create on your B2C instance fails, as it is against this policy. You may create a user record to grant fine grained roles on the B2C instance for a user, but the user must be bound against a user profile in Account Manager via the property `external_id`, which must carry the ID of a user previously created (or existing beforehand) in your org in Account Manager.

There are some examples for this in the wiki at https://github.com/SalesforceCommerceCloud/sfcc-ci/wiki/Cheatsheet-and-Examples#local-user-creation, look out for _To create a new local user on a B2C Commerce instance who uses Account Manager to authenticate run_ in that chapter:

Hope that helps.

**Comment by lornadsilvasonos** [comment]
The user already exists in our Account Manager but does not have a local account on the instance. From what you have said, I tried the command and get the following error 

`Error: An error occurred while decoding the request. There's a value constraint violation of property '$.email' in document 'user'.`

I am not sure what the error means over here. Could you let me know?

**Comment by tobiaslohr** [comment]
Sounds like you are not passing the email property or a syntactical invalid value. Can you share the command including the values passed, specifically the JSON value passed for the `--user`? Please anonymise your values before passing them here!

**Comment by lornadsilvasonos** [comment]
sfcc-ci user:create --instance <instance_hostname>  --login someid@sonos.com --user '{"external_id":"someid@sonos.com"}'

**Comment by tobiaslohr** [comment]
Apparently the property `email` and also `last_name` are required in the user document. Also please note, that `external_id` must be the ID (more precisely the UUID) of the user in Account Manager. So, in your example, the command should look like:

```
sfcc-ci user:create --instance <instance_hostname> --login someid@sonos.com --user '{"external_id":"<uuid-of-user-in-accountmanager>", "email":"someid@sonos.com", "last_name":"<the-last-name>"}'
```

The UUID of the user in Account Manager can be seen in Account Manager when navigating to the respective user in your org or via the CLI by using command:

```
sfcc-ci user:list --login someid@sonos.com
```

Note, that you have to have appropriate permissions in Account Manager to do so, e.g. Account Administrator role.

**Comment by lornadsilvasonos** [comment]
This one really helped. Not that the account I used for login did not have Administrator role in the Account Manager but I was still able to create the user. Could we also update https://quip.com/fmfVACpMxK1J to reflect the addition of email and last_name in the command? Thank you once again.

**Comment by tobiaslohr** [comment]
I've updated the Quip. Please note, that we have moved the Cheatsheet and Examples into the wiki at https://github.com/SalesforceCommerceCloud/sfcc-ci/wiki/Cheatsheet-and-Examples.

**Comment by lornadsilvasonos** [comment]
Thank you. I will refer to the new wiki article. Once again, thanks for your prompt response.

**Comment by lornadsilvasonos** [comment]
Hi, 

I have been using the `sfcc-ci user:create --instance <instance_hostname> --login someid@sonos.com --user '{"external_id":"<uuid-of-user-in-accountmanager>", "email":"someid@sonos.com", "last_name":"<the-last-name>"}'`  successfully for about 2 weeks. This week I get an error when I try this command. `Error: Insufficient permissions. Ensure your API key has permissions to perform this operation on the instance.`
