### ISSUE TITLE
Allow JSON file to be passed as export units configuration for instance:export

### ISSUE THREAD

**Issue by karsov-aiops** [SalesforceCommerceCloud/sfcc-ci#144]
Hello,

It would be great to have an option to pass a configuration file for export units to the `instance:export`

Currently there is an option `--data '{"global_data": {"meta_data": true}}'`.

**Proposed solution**

Add an option `--data-file config.json` to be parsed and used for export units.

Regards,
Kris

**Comment by tobiaslohr** [comment]
Hi @karsov-aiops, I like the idea of passing the export config as a file. Do you plan to contribute a PR for this?

**Comment by karsov-aiops** [comment]
Hi @tobiaslohr ,

I might create a PR for that, but not sure when I will have spare time.
Maybe in the following month.

**Comment by tobiaslohr** [comment]
Fixed with #183
