### ISSUE TITLE
<org> id or name? Where to get this value 

### ISSUE THREAD

**Issue by chenliangborngroup** [SalesforceCommerceCloud/sfcc-ci#147]
Hi there, 
I have a question about what should I put in the <org>.. I tried the org id, org name, our hostname, but none works.. can you give me an example of where to get the <org>? Many thanks!! 

This is my testing: 
```
BORNUSLIANG:sfcc-ci chen.liang$ sfcc-ci user:create --org 49233b92-c5a2-4fbc-8fc2-ee9a98c45b58 --login test@borngroup.com --user '{"firstName":"Test", "lastName":"test", "roles": ["xchange-user","doc-user"]}'
**_Error: Unknown org 49233b92-c5a2-4fbc-8fc2-ee9a98c45b58_**
```

This is the instruction in the cheat sheet: 

To create a new user in Account Manager for your org run:

$ sfcc-ci user:create --org <org> --login <email> --user '{"firstName":"<firstName>", "lastName":"<lastName>", "roles": ["xchange-user","doc-user"]}'
<org> is the org in Account Manager the new user is created in

Best, 
Chen

**Comment by chenliangborngroup** [comment]
I just test it out. It is neither the name or the id shown in the account manager.

**Comment by tobiaslohr** [comment]
@chenliangborngroup It is the org name, which is expected there for `--org <org>`. In order to see which orgs you have permissions for, you may want to use `sfcc-ci org:list` and use the org name from that list.

**Comment by anigandhe** [comment]
Thanks. I was trying that even before reading this thread. But I keep getting 
Error: Ambiguous options. Pass either -o,--org or -i,--instance.

I am on windows and using sfcc-ci-win exe

My command is as follows. please note that my orgnization has space in the name
sfcc-ci-win user:create --org "org name" --login fname.lname@org.com --user '{"firstName":"firstname", "lastName":"lastname", "roles": ["xchange-user","doc-user"]}'

Appreciate any help

**Comment by tobiaslohr** [comment]
@anigandhe the error `Error: Ambiguous options. Pass either -o,--org or -i,--instance.` is returned, in case you don't pass a value to `--org` or `--instance` or if you pass a value to both at the same time (non valid use case).

can you try quoting your value like this:

`sfcc-ci user:create --org 'my org name' ...`
