### ISSUE TITLE
Issue while activating code version

### ISSUE THREAD

**Issue by venkataraoetg** [SalesforceCommerceCloud/sfcc-ci#152]
I'm able to create a code version on a staging instance but not able to activate the code version. I'm getting "certificate error" when I try to activate the deployed code version.

**sfcc-ci client:auth $API_KEY $API_SECRET --renew**

**sfcc-ci code:deploy FUN_SHOP_$CODEBUILD_BUILD_NUMBER.zip -i $SFCC_INSTANCE_NAME -c $CODEBUILD_SRC_DIR/funimation.p12 -p $P12_Password**

**sfcc-ci code:activate FUN_SHOP_$CODEBUILD_BUILD_NUMBER -i $SFCC_INSTANCE_NAME**

There are no options to add 2-factor certificate path & password for "**code:activate**" command.

Even tried to activate the code version in the "**code:deploy**" command with option -a:

**sfcc-ci code:deploy FUN_SHOP_$CODEBUILD_BUILD_NUMBER.zip -i $SFCC_INSTANCE_NAME -c $CODEBUILD_SRC_DIR/funimation.p12 -p $P12_Password -a true**

Please suggest to proceed it further.

**Comment by tobiaslohr** [comment]
When you activate the code version with:

```
sfcc-ci code:activate FUN_SHOP_$CODEBUILD_BUILD_NUMBER -i $SFCC_INSTANCE_NAME
```
please make sure, that `$SFCC_INSTANCE_NAME` does not carry the cert version of the host name, e.g. `cert.staging.something...`, but `staging.something...` or `staging-something...`

**Comment by venkataraoetg** [comment]
I was able to resolve the issue. The issue was due to SSL certificate strict validations on staging. I have bypassed it from dw.json file & was able to trigger build successfully.

Thanks!

**Comment by DenyVeyten** [comment]
@tobiaslohr in my case `staging.something` returns timeout error while `staging-something` is fine. So that `code:deploy --activate` does not work as it transforms `cert.` prefixed hostname into dotted version. Can raise it as a separate issue if it's not tracked already.
