### ISSUE TITLE
user:create Error - Ambiguous options. Pass either -o,--org or -i,--instance

### ISSUE THREAD

**Issue by anigandhe** [SalesforceCommerceCloud/sfcc-ci#154]
Hello I am getting below error while creating a new user in Account Manager
Error: Ambiguous options. Pass either -o,--org or -i,--instance.

I am on windows and using sfcc-ci-win exe

My command is as follows. please note that my orgnization has space in the name
sfcc-ci-win user:create --org "org name" --login fname.lname@org.com --user '{"firstName":"firstname", "lastName":"lastname", "roles": ["xchange-user","doc-user"]}'

Appreciate any help

**Comment by tobiaslohr** [comment]
Hi @anigandhe, you've posted this already and I've replied there at https://github.com/SalesforceCommerceCloud/sfcc-ci/issues/147#issuecomment-637394272:

> the error Error: Ambiguous options. Pass either -o,--org or -i,--instance. is returned, in case you don't pass a value to --org or --instance or if you pass a value to both at the same time (non valid use case).
>
> can you try quoting your value like this:
>
>`sfcc-ci user:create --org 'my org name' ...`

**Comment by sftschaerff** [comment]
As the issue seems to be solved, I will close it.
