### ISSUE TITLE
sandbox.js line 471 ReferenceError: body is not defined

### ISSUE THREAD

**Issue by AndersonDaSilvaOSF** [SalesforceCommerceCloud/sfcc-ci#155]
Inside lib/sandbox.js, line 471 you will get a **ReferenceError: body is not defined** because you are trying to access a variable named body that does not exist. It should be res.body

**Comment by tobiaslohr** [comment]
True, thanks for the hint @AndersonDaSilvaOSF. Do you plan to submit a PR to fix this?
