### ISSUE TITLE
Request for sandbox:create Time To (Stop?) option.

### ISSUE THREAD

**Issue by ralgh** [SalesforceCommerceCloud/sfcc-ci#162]
Currently when creating a new on demand sandbox there is no option to assign an amount of time for a sandbox to be flagged as inactive and therefor be stopped. Sandbox owners need to manually stop a sandbox to throttle it down to burn the .3 credits per minute. Now understanding this is not necessarily in the financial interest of SFCC to provide this functionality I do believe it is something that would be beneficial to the developer community. 

```
-ts, --tts <hours> Number of hours since last activity the sandbox will stopped

Example:
$ sfcc-ci sandbox:create -r my-realm --tts 6
```

I'm not sure how technically feasible it is for the API to determine that last activity time. I'm assuming this would monitor the non-system user logs.

**Comment by tobiaslohr** [comment]
Thanks @ralgh for raising the request. The request makes definitely sense. The CLI tool itself provides only a small layer of business logic on top of the existing API (e.g. the sandbox API). We can expose a new command or enhancements of existing commands, if the APIs expose this functionality. A new functionality, like the one you've proposed would therefore first be made available in the sandbox API before we can expose it as a CLI in the tool. I suggest you raise this feature request for the sandbox API in our Chatter group "B2C Ondemand Sandboxes Technical Support".

**Comment by tobiaslohr** [comment]
@w6bedi FYI

**Comment by ralgh** [comment]
OK Thanks @tobiaslohr, I'll psot my request on the Sandbox API Chatter Group.

**Comment by sftschaerff** [comment]
As the issue seems to be solved, I will close it.
