### ISSUE TITLE
Javascript sfcc.instance.import callback function with data as of cli 

### ISSUE THREAD

**Issue by Gektorian** [SalesforceCommerceCloud/sfcc-ci#170]
When we use CLI to import data zip we are getting comprehensive data as a response to the action. In the Javascript version callback function only manages errors and does not return status of the job, link to log files, or other data which is showed by CLI version of the same action.

Did I miss the way how from the callback function get the same level of data as from console version or such functionality is just missing?

**Comment by sftschaerff** [comment]
Hi @Gektorian,

the CLI tool is using the exact same methods as one can use with javascript.
With the command `sfcc-ci instance:import` you should see a job ID, which you can use as input parameter of the command `sfcc-ci job:status` to get informations about your job.

I hope this help!

Best
Tobias

**Comment by Gektorian** [comment]
Hi @sftschaerff, when I checking the documentation I only see that callback function will work only with "errors":
![image](https://user-images.githubusercontent.com/3693219/89964739-f3f67d80-dc85-11ea-9ae4-1bd725ee449d.png)

Should I assume that I can OOTB use extra input parameters of the callback function as:
```
sfcc.instance.import(instance, file_name, token, function(err, jobStatus) {
// ... logic goes here...
var jobID = jobStatus.status;
}
```

**Comment by sftschaerff** [comment]
Hi @Gektorian,

I just had another look at the code and here is what I found:
When you use the upload method, the import file is directly uploaded to a Commerce Cloud instance, it's not done via a job.
When you use the import method, the 'sfcc-site-archive-import' is triggered, to import the uploaded archive.

So only with the import method you might receive job informations. The call could look like the following:
`sfcc.instance.import(options.baseUrl, options.fileName, token, function (error, result) {}`.

The result object contains the job informations.

Regards
Tobias

**Comment by Gektorian** [comment]
I will work on my solution with this information in mind. Thanks a lot!
