### ISSUE TITLE
MFA and sandbox APIs

### ISSUE THREAD

**Issue by NicoloMenandroDiana** [SalesforceCommerceCloud/sfcc-ci#182]
Hi,

I'm trying to automate the "sfcc-ci sandbox:stop" but the authentication using sfcc-ci client:auth $CLIENT_ID $SECRET $USER $PASSWORD fails.
The user I'm trying to authenticate doesn't have a device paired and has the right Sandbox API permissions and is enabled.

Follow the authentication response:
`{
  response: {
    debugId: 1,
    headers: {
      date: 'Wed, 14 Oct 2020 10:33:28 GMT',
      'content-type': 'application/json',
      'transfer-encoding': 'chunked',
      connection: 'close',
      'set-cookie': [Array],
      'x-frame-options': 'SAMEORIGIN',
      pragma: 'no-cache',
      'cache-control': 'no-store',
      'accept-ranges': 'bytes',
      vary: 'Accept-Charset, Accept-Encoding, Accept-Language, Accept',
      'strict-transport-security': 'max-age=15724800; includeSubDomains'
    },
    statusCode: 400,
    body: {
      error_description: 'Resource owner authentication failed',
      error: 'invalid_grant'
    }
  }
}
`

The same "sfcc-ci client:auth $CLIENT_ID $SECRET" command using my account (with the Sandbox API permission) works after the MFA with my paired device.

I suppose that the problem is that since the 1st of October MFA is mandatory and the AM user must have the device associated. Could it be? How could I solve this problem?

**Comment by macleodg** [comment]
We are also seeing this. All of the other suggestions I can find are for folk to remove 2FA from the user designated for CLI sandbox actions, but that is no longer an option.

**Comment by macleodg** [comment]
@NicoloMenandroDiana - @tobiaslohr got back to me via the sfcc-ci slack channel with:

"the user you use to authenticate for automation use of the CLI must only have the Sandbox API User role. this role you’d have to deactivate 2FA for in your account manager org"

I'm going to have to look into if our org can/wants to modify our 2FA settings to allow for automation around sandboxes.

**Comment by tobiaslohr** [comment]
@NicoloMenandroDiana @macleodg The sandbox API now supports using a client_credentials grant (an authenticated API client, not a user) to manage sandbox. Since a user authentication is not involved, there is no MFA to be done, hence it supports the automation scenario.

To do this go to your API client, assign role `Sandbox API User` with tenant being your realm you want to manage sandboxes for. Then for authentication just run `$ sfcc-ci client:auth <client-id> <secret>`

**Comment by NicoloMenandroDiana** [comment]
@tobiaslohr this is great news!
thank you so much
