### ISSUE TITLE
Creation of API Client ID

### ISSUE THREAD

**Issue by roy-tan** [SalesforceCommerceCloud/sfcc-ci#196]
We need to provide an extensive number (tens of thousands) of API access so doing this via the Account Manager user interface is not feasible. Appreciate if we can have a sfcc-ci command to create the API client id so we can automate this process.

**Comment by tobiaslohr** [comment]
This was fixed by #350 and is now available as part of release v2.11.0 (see https://github.com/SalesforceCommerceCloud/sfcc-ci/releases/tag/v2.11.0)
