### ISSUE TITLE
User Creation date for Audit purpose

### ISSUE THREAD

**Issue by mganoo** [SalesforceCommerceCloud/sfcc-ci#197]
I need to read the user data (maybe history), so it can show me when the user was created. I need this report to submit to our external auditors. See the attached Account Manager screenshot. Ideally, on this screen so I can submit it to the auditors.
![Screen Shot 2022-11-16 at 6 34 07 AM](https://user-images.githubusercontent.com/69092340/202182225-7f5db50c-fd75-4757-ab25-e3a144692104.png)

**Comment by tobiaslohr** [comment]
@mganoo Thanks for raising this. With https://github.com/SalesforceCommerceCloud/sfcc-ci/pull/336 we have enhanced the user management related commands (`sfcc-ci user:list`) to return the last login date per user. For the creation date the data is unfortunately not (yet) available via the respective APIs. 

However, you've mentioned already the user history (audit records in Account Manager to be precise). The audit records can be used to read the user's creation data, however it only available on a per user basis thus it cannot be made of the user list now. Can you provide some details around the audit itself? Is it right to assume, that you are seeking to generate a list/report of all your users incl. their creation date?

**Comment by mganoo** [comment]
Hello,

I appreciate you getting back to me on this.

The purpose of the ask was auditor wants to see a screen that can show them
the date of creation for the user.
So they can pick a handful of users from the current year and ask me
for the details, like the ticket number approved by the manager to create
the login etc.
Not sure why it can't be shown on the following screen

[image: image.png]

I hope I have answered your question. Feel free to let me know if you have
any more questions.



------------------------------

Mac Ganoo

Sr. Dev Manager, Sr. Architect Salesforce Solutions & SDM

**Comment by tobiaslohr** [comment]
Hi @mganoo, with #341 support has been added to work with audit logs and fetching the audit logs for changes made to a user. This includes the possibility to fetch all audit logs:

`sfcc-ci user:list --login <login> --auditlogs`

as well as fetching a user's creation log incl. the creation date:

`sfcc-ci user:list --login <login> --auditlogs --json | jq '.content[] | select(.eventType == "USER_CREATED")'`

The change is available in master, but has not yet been released. It will most probably be part of the next release (`v2.11.0`).

**Comment by mganoo** [comment]
Thanks for the update.

------------------------------

Mac Ganoo

Sr. Dev Manager, Sr. Architect Salesforce Solutions & SDM
