### ISSUE TITLE
client:auth won't ingore dw.json file

### ISSUE THREAD

**Issue by fenomchris** [SalesforceCommerceCloud/sfcc-ci#200]
When running the client auth command with client-id and client-password parameters, the plugin still tires to use dw.json file credentials. As we use MFA for all users, this causes auth to fail for everyone. Is there a way to force ignore the dw.json file when authenticating?

**Comment by DenyVeyten** [comment]
+1 for the ability to ignore username and password from dw.json

**Comment by nickpalmigiano** [comment]
The fix for this should be included in #245

**Comment by tobiaslohr** [comment]
Fixed by #499
