### ISSUE TITLE
B2C sandbox creation

### ISSUE THREAD

**Issue by suhel1612** [SalesforceCommerceCloud/sfcc-ci#202]
Hello Experts,

I am stuck with sfcc-ci auth:login is failing to authenticate using OAUTH2. What should be the value of SFCC_LOGIN_URL? I wonder if there is a step by step guide for the authentication steps to be followed before the Sandbox creation steps as outlined on the cheatsheet https://sfdc.co/sfcc-cli-cheatsheet
Thanks for your time.
Regards,
Suhel

**Comment by tobiaslohr** [comment]
@suhel1612 What exactly is failing? The SFCC_LOGIN_URL is meant to be the host name of the Account Manager. As Account Manager is multi-tenant, you don't need to adjust SFCC_LOGIN_URL as by default account.demandware.com is being used.

What steps are missing in the README.md and in the wiki?

**Comment by tobiaslohr** [comment]
@suhel1612 Is this still relevant or can we close it?

**Comment by tobiaslohr** [comment]
@suhel1612 Any final thoughts on the ticket you created or can we close this?

**Comment by suhel1612** [comment]
hi,
the ticket can be closed.... thnx
