### ISSUE TITLE
sfcc-ci auth:login - unable to authenticate

### ISSUE THREAD

**Issue by suhel1612** [SalesforceCommerceCloud/sfcc-ci#203]
Hello Experts,
I am trying to create a Commerce cloud B2C On-demand Sandbox. 

When I execute 'sfcc-ci auth:login' I do get the login screen asking for user name followed by password and finally a blank screen and i dont got the MFA authentication request on my mobile.

Any thoughts please?
![verify screen](https://user-images.githubusercontent.com/58297333/109965124-70b27d00-7ce6-11eb-9967-610c7e6da315.PNG)

**Comment by tobiaslohr** [comment]
@suhel1612 is MFA working well when you log into Business Manager (e.g. on a sandbox)?

**Comment by tobiaslohr** [comment]
Well, this sounds like a general access problem, and not related to the CLI tool at all. I suggest you open a Case with our Support Team.

**Comment by tobiaslohr** [comment]
@suhel1612 Can we close this ticket?

**Comment by suhel1612** [comment]
Yes please
