### ISSUE TITLE
Getting Error: Authentication failed: Resource owner authentication failed error

### ISSUE THREAD

**Issue by mohanckulkarni** [SalesforceCommerceCloud/sfcc-ci#213]
I am trying to use the below interactive auth command using sfcc-cli too. 

sfcc-ci client:auth $API_KEY $API_SECRET $API_USER $API_USER_PW

I am getting Error: Authentication failed: Resource owner authentication failed error when i try to authenticate with my account manager user and password. Not sure why. 

The same user name and password works fine when i use them to login to Account Manager manually. Even tried resetting the password but still getting the same authentication failed error.

**Comment by tobiaslohr** [comment]
Most likely this is an issue with your user password. Please try quoting your password with `'` and try again. Also bear in mind, that for running automations you don't have to authenticate a user anymore, but you only need the client id and secret. Roles and tenant filters can be assigned to API clients, like for managing sandboxes automatically.

**Comment by mohanckulkarni** [comment]
Thanks Tobias for replying back.

I don’t think it’s an issue with my user password. I am able to use the same password to log into Account Manager. I tried setting the API_USER_PW with quotes and call the below command:

sfcc-ci client:auth $API_KEY $API_SECRET $API_USER $API_USER_PW

It failed with the same error.

What is command we need to use for authenticating with client id and secret to run automations? I used sfcc-ci client-auth $API_KEY $API_SECRET and was able to login but can’t execute the user create commands below


sfcc-ci user:create --org ORG --login ***@***.*** --user '{"firstName": "'Test'", "lastName": "'User'"}'

Error: Authentication invalid. Please (re-)authenticate by running ´sfcc-ci auth:login´ or ´sfcc-ci client:auth´

Would be great help if you can guide me as our automation scripts to create users and assign roles per tenant are failing due to this issue. We use these automation scripts to create users with needed roles in staging and our production DWRE instance.

Regards,

Mohan Kulkarni | Sr. Solutions Architect | eCommerce
T: 704.426.8218 | F: 704.357.0374 | ***@***.***

[Description: Description: Description: Description: Description: BelkLogo_4_color.jpg]
Belk, Inc.  | 2801 W. Tyvola Road Charlotte, NC 28217 | belk.com

From: Tobias Lohr ***@***.***>
Date: Wednesday, May 26, 2021 at 10:44 AM
To: SalesforceCommerceCloud/sfcc-ci ***@***.***>
Cc: Mohan Kulkarni ***@***.***>, Author ***@***.***>
Subject: Re: [SalesforceCommerceCloud/sfcc-ci] Getting Error: Authentication failed: Resource owner authentication failed error (#213)

Most likely this is an issue with your user password. Please try quoting your password with ' and try again. Also bear in mind, that for running automations you don't have to authenticate a user anymore, but you only need the client id and secret. Roles and tenant filters can be assigned to API clients, like for managing sandboxes automatically.

**Comment by tobiaslohr** [comment]
@mohanckulkarni To run automations in fact you don't need anymore the user to authenticate. You only need a client. (BTW, you can then finally activate MFA for all roles in your Account Manager org.) 

Did you assign the `Account Administrator` role to your API client? If not, please do that, as it's required to give user management permissions to your API client. If you don't see the `Account Administrator` role for selection in your API client details, I suggest you open a Support Case and have support assigning it to your API client on your behalf.

**Comment by tobiaslohr** [comment]
Hi @mohanckulkarni , Can we close this?
