### ISSUE TITLE
instance.import stop working after recent changes

### ISSUE THREAD

**Issue by navyhod** [SalesforceCommerceCloud/sfcc-ci#217]
Hi Experts!
Today we faced the problem with importing site archive via sfcc-ci. Changes were made in the following PR https://github.com/SalesforceCommerceCloud/sfcc-ci/commit/39217f8ddcf3046cd3a0fb7a77e0bf6924c48292#diff-d3a527ebc15848de99aed98f38fb6fa47ad5d42ee8d9f6c74b3086bf9be5c36c on line 296.
Could you please let me know one this problem will be resolved?

Thanks!
Best regards, Oleksandr

**Comment by tobiaslohr** [comment]
@navyhod Can you please post the exact error message here? Also note, that we haven't build a new release yet. So, even if in master, you should always use an official release.

**Comment by tobiaslohr** [comment]
@jbachelet Something you can check?

**Comment by navyhod** [comment]
Hi @tobiaslohr 

error message is quite clear - "Parameter job_params must either be an array". And this error message comes from instance.api.import method. I guess that it would be enough just to wrap parameters inside import function but I'm not sure that  this is all required actions that should be made.
Thanks!

**Comment by tobiaslohr** [comment]
@navyhod So, it's an issue in the JS API `instance.import` and not in the CLI command `sfcc-ci instance:import`?

**Comment by navyhod** [comment]
@tobiaslohr correct

**Comment by tobiaslohr** [comment]
@navyhod A fix was provided by @jbachelet and merged into master. Can you please re-test on your side?

**Comment by tobiaslohr** [comment]
Hi @navyhod, may I ask you to review the fix provided for this and let us know, if this fixes your issue? We'd like to build a release afterwards. Thanks a lot!

**Comment by jonathansayag** [comment]
Hi @tobiaslohr, the fix solved the issue on my side.

**Comment by tobiaslohr** [comment]
Thanks a lot @jonathansayag for the feedback!

**Comment by navyhod** [comment]
Hi @tobiaslohr, everything works fine. Thanks and sorry for late reply.

**Comment by tobiaslohr** [comment]
thanks for confirming @navyhod
