### ISSUE TITLE
Regression: webDAV-functionality broken on Windows

### ISSUE THREAD

**Issue by KennethRobbeFrucon** [SalesforceCommerceCloud/sfcc-ci#228]
The following line was updated in version 2.7.0, but this breaks all webDAV-functionalities on Windows:

https://github.com/SalesforceCommerceCloud/sfcc-ci/blob/613bf7478afcba72daf3831ed1c0cbccc92a33c2/lib/webdav.js#L26

It uses path.join to join two path segments. However, path.join() is meant to interact with file paths, while this is an URI. This results in a path with backslashes on Windows, which isn't a valid URI. This can be seen by running the unit tests on Windows. All tests for lib/webdav.js fail due to these types of errors:

`AssertionError: expected '\\on\\demandware.servlet\\webdav\\Sites\\cartridges\\mycode.zip' to equal '/on/demandware.servlet/webdav/Sites/cartridges/mycode.zip'`

In the past, the path was just concatenated:
https://github.com/SalesforceCommerceCloud/sfcc-ci/blob/074cc74082c874bc5cc4f934ebd6d8964f186ad0/lib/webdav.js#L26

**Comment by KennethRobbeFrucon** [comment]
@jbachelet / @tobiaslohr Could you please look into this as you did / merged the change that caused the issue? Was this just an oversight or was there a specific reasoning behind using path.join here?

**Comment by tobiaslohr** [comment]
@KennethRobbeFrucon Agree! This is a bug and from what I can see, there was not a specific reason `path.join` was used instead. @jordanebachelet please correct me if I'm wrong

**Comment by jbachelet** [comment]
Apologize for the issue, I was only able to test it on mac, where it works fine.
We should revert this change then

**Comment by tobiaslohr** [comment]
@jbachelet Thanks. Do you have bandwidth to do this?

**Comment by zlatinz** [comment]
@jbachelet @tobiaslohr will https://nodejs.org/api/url.html#url_new_url_input_base work instead?

**Comment by tobiaslohr** [comment]
Provided a fix in https://github.com/SalesforceCommerceCloud/sfcc-ci/pull/233, please review and approve
