### ISSUE TITLE
Can not get headless authentication to work

### ISSUE THREAD

**Issue by MrWWeber** [SalesforceCommerceCloud/sfcc-ci#229]
When configuring my dw.json file - I believe I am placing the correct values within the file - however the SFCC-CI application still attempts to spawn a browser when using the  auth:login   option.

Is there another way to get headless authentication to work? I am attempting to place this tool within a CI/CD agent's build pipeline. Documentation here mentions headless - but I'm not able to figure out how to get it to work.

Am I just doing something dumb?

**Comment by tobiaslohr** [comment]
@MrWWeber did you place a client id and a client secret in the `dw.json`?

**Comment by MrWWeber** [comment]
Yes - we were using the wrong auth type and once we fixed that and our client config in sfcc + dw.json we were good. I'll close this out.

**Comment by tobiaslohr** [comment]
Thanks for confirming @MrWWeber
