### ISSUE TITLE
sfcc-ci sandbox:ips no flag for instance, output confusing

### ISSUE THREAD

**Issue by nek4life** [SalesforceCommerceCloud/sfcc-ci#240]
The output is confusing for sandbox:ips which sandbox is it using to get the IPs addresses? According to Salesforce there should be 3 outgoing IPs for each sandbox, however there does not appear to be a way to specify which sandbox and the verbiage says sandboxes

Here is the help instructions

List inbound and outbound IP addresses for sandboxes

Options:
  -j, --json  Formats the output in json
  -h, --help  output usage information

  Examples:

    $ sfcc-ci sandbox:ips
    $ sfcc-ci sandbox:ips --json

**Comment by nek4life** [comment]
I'm looking at the swagger api docs now. I'm thinking SF support may be wrong here... working with them. Will close if that is the case.

**Comment by tobiaslohr** [comment]
@nek4life The commands make use of the sandbox admin API `GET /system`. There is no sandbox or instance specific input required.

**Comment by tobiaslohr** [comment]
hi @nek4life, can we close this?

**Comment by nek4life** [comment]
Yup, there documentation is wrong and there are only one set of IPs and not a set of IPs per sandbox
