### ISSUE TITLE
Allow client:auth to force client_credential grant

### ISSUE THREAD

**Issue by hnestmann** [SalesforceCommerceCloud/sfcc-ci#245]
If dw.json is filled with user name and password. SFCC-CI will add "grant_type":"password" to the auth. This auth doesn't work sometimes, forcing the user to client up dw.json

**Comment by tobiaslohr** [comment]
Thanks for raising @hnestmann! There are two options I see:

* Change the behaviour of command `sfcc client:auth` to only accept explicit arguments passed in case you have at least some arguments passed already. In your case, if you are passing client id and secret explicitly it will not read user creds from another source, like from the `dw.json` but expects them as being passed explicitly as well
* Change command `sfcc client:auth` and only allow client_credential grant, but not resource_owner_password_credentials grant anymore. Reason being is, that with the Sandbox API now supporting client_credentials grant fully for automation use cases, I don't see any other use case left, which requires resource_owner_password_credentials anymore. Note, we would still allow a user to authenticate interactively using `sfcc-ci auth:login`

In any case, both options above are breaking changes and would have to walk into a new major version.

Thoughts?

**Comment by DenyVeyten** [comment]
+1 for resolving this issue, in our use case during local development we use JS API scripts whenever possible, but `instance:export` is not supported (another enhancement to report 😄), so we have to use `client:auth` that inevitably uses user from dw.json.
@tobiaslohr could you consider backward compatible change like the additional flag mentioned, to release it for 2.x version?

**Comment by jlbruno** [comment]
Can we get one of these fixes merged? 
This has been open for two years, and it's completely broken when trying to use `client:auth` if the `password` in your `dw.json` is an access key instead of your account manager password.

**Comment by tobiaslohr** [comment]
@jlbruno We have merged #499 and will build a new release. For the records: you could have simply changed the working directory which does not contain the dw.json and execute the command from there. Then it does not pick up the user credentials from the dw.json, as it's not finding it any longer.

**Comment by tobiaslohr** [comment]
Change is backwards compatible, hence removing label #api-change
