### ISSUE TITLE
sandbox:get -s xxxx -O option always redirects to us01 host

### ISSUE THREAD

**Issue by jorgehernandezSF** [SalesforceCommerceCloud/sfcc-ci#250]
This line of code:
https://github.com/SalesforceCommerceCloud/sfcc-ci/blob/master/lib/sandbox.js#L26
is hardcoded to **us01**
which means that the 
sfcc-ci sandbox:get -s xxxx -O command always sends you to the us01 host, which no longer exists.

**Comment by tobiaslohr** [comment]
Thanks for raising @jorgehernandezSF! This is indeed the last leftover of us01 being the only sandbox cluster. We requested an API change of the Sandbox API. This change is for `GET /sandboxes`, `GET /sandboxes/{id}`, `POST /sandboxes` to return the host name of the sandbox as part of the SandboxModel, which is now being made available.
