### ISSUE TITLE
License not clear

### ISSUE THREAD

**Issue by amahe** [SalesforceCommerceCloud/sfcc-ci#254]
Hi SFCC-CI team, 

When i have a look at the projet  you say that the BSD-3 licence  apply. 
In the [license file ](https://github.com/SalesforceCommerceCloud/sfcc-ci/blob/master/LICENSE.txt), the first line says that this product depends on salesforce. 
So is-it dependant of Salesforce or the community ?
Could be great to clarify that point for evryone. 

Kind regards

**Comment by tobiaslohr** [comment]
Hi @amahe,
we have followed our Salesforce open sourcing processing when open sourcing the CLI tool and thus are using the same type of license as for other Salesforce open source tools. For specific questions on type of licenses I kindly refer to contacting the Salesforce legal at https://www.salesforce.com/company/legal/

**Comment by tobiaslohr** [comment]
Is there any other question on that or can we close this?

**Comment by amahe** [comment]
Yes it's ok, can close then. Thx.
