### ISSUE TITLE
Self-signed Certificates

### ISSUE THREAD

**Issue by t-s-s** [SalesforceCommerceCloud/sfcc-ci#255]
https://github.com/SalesforceCommerceCloud/sfcc-ci/blob/1199c9d1ca67ba2f27d2517b7ec4647bd1667594/lib/webdav.js#L37

Shouldn't this be configurable in the command line interface not just via dw.json

I noticed there is a --selfsigned option but it is ignored.

My understanding is that we should be generating the client certificate and signing it with the key provided by Salesforce rather than using the master certificate provided by SFCC even if it is for CI/CD.

https://documentation.b2c.commercecloud.salesforce.com/DOC1/topic/com.demandware.dochelp/content/b2c_commerce/topics/site_development/b2c_creating_and_using_certificates_for_code_deployment.html

**Comment by tobiaslohr** [comment]
Hi, thanks for raising this. I don't see a reason, why it should only be supported via dw.json. It should be supported via global flag `--selfsigned`. Do you mind submitting a PR for this?
