### ISSUE TITLE
SFCC CLI "SLAS" commands not working

### ISSUE THREAD

**Issue by nvenna39** [SalesforceCommerceCloud/sfcc-ci#258]
Hi Team,
One of our customer noticed an issue with the SFCC CLI commands in the README.md
Eg: 
sfcc-ci slas:client:list
Error: Unknown command `slas:client:list`. Use `sfcc-ci --help` for help.

slas commands looks like not working.

Could you please review and let us know if any issues with the commands and provide suggestions here. Thank you!

**Comment by tobiaslohr** [comment]
Latest release v2.8.0 (https://github.com/SalesforceCommerceCloud/sfcc-ci/releases/tag/v2.8.0) contains the SLAS related commands. Closing this now
