### ISSUE TITLE
sfcc-ci library code.diffdeploy issue on win

### ISSUE THREAD

**Issue by vkusok** [SalesforceCommerceCloud/sfcc-ci#266]
Hi All,

I am observing an issue with diffdeploy on windows.
My research has shown that diffdeploy method is using globby which is expecting patterns without backslashes and if the string contains backslash char, such chars will be ignored.

E.g. this part of code:

`const files = await globby(directories.map(directory => path.join(directory, 'cartridges/**/*')), {
            ignore: ignoreAcrossDirectories
        });`

After path.join we will have `cartridges\**\*` which results `cartridges***` for globby lib. And as a result, the system will not be able to find files matching the pattern.

The solution can be in replacing path.join with straight POSIX specifying to avoid backslashes.

Example of working solution with path.join to path.posix.join replacement:
`const files = await globby(directories.map(directory => path.posix.join(directory, 'cartridges/**/*')), {
            ignore: ignoreAcrossDirectories
        });`

Please share your thoughts and if you've faced this issue let me know and I'll submit a pull request.

**Comment by tobiaslohr** [comment]
Thanks for raising @vkusok! 

@jordanebachelet Can you please give your thoughts on that?

**Comment by tobiaslohr** [comment]
Thanks much for looking into this @jbachelet! Please have a look @vkusok if this fixes your issue on Windows.
