### ISSUE TITLE
Colors infinite loop

### ISSUE THREAD

**Issue by ecRobertEngel** [SalesforceCommerceCloud/sfcc-ci#268]
Due to (the intentional) broken colors.js version 1.4.1 sfcc-ci is currently not working. 

**The solution is to fix the dependency to version 1.4.0.**
Long term I would try to switch to a community fork of colors as I except more trouble with this package.

I also noticed that colors is part of the dependencies and dev-dependencies, which can be removed.

**Comment by johnang-del** [comment]
+1, this is breaking our CI pipelines right now

**Comment by mrkpatchaa-sf** [comment]
Might be related but our pipeline is running for 20 min now only on sfcc-ci auth.

**Comment by mrkpatchaa-sf** [comment]
So this is the reason.
https://developers.slashdot.org/story/22/01/09/2336239/open-source-developer-intentionally-corrupts-his-own-widely-used-libraries

https://github.com/Marak/colors.js/issues/285

**Comment by mrkpatchaa-sf** [comment]
Temporarily fixed by patching the package.
https://www.npmjs.com/package/patch-package

**Comment by tobiaslohr** [comment]
Fix with release https://github.com/SalesforceCommerceCloud/sfcc-ci/releases/tag/v2.8.1
