### ISSUE TITLE
2.9.0 updated node-fetch

### ISSUE THREAD

**Issue by DenyVeyten** [SalesforceCommerceCloud/sfcc-ci#280]
Looks like after updating from 2.8.0 to 2.9.0 this error pops up with the usage of JS API:
![image](https://user-images.githubusercontent.com/11442834/150950137-3b29f9c3-c548-44ef-b7e8-40401f43b3dc.png)

Node version: v16.13.1

**Comment by tobiaslohr** [comment]
This is available in patch https://github.com/SalesforceCommerceCloud/sfcc-ci/releases/tag/v2.9.1
