### ISSUE TITLE
"user:create" -  "TypeError: Cannot red property 'split' of null"

### ISSUE THREAD

**Issue by fy2sysnotify** [SalesforceCommerceCloud/sfcc-ci#295]
I am getting "TypeError: Cannot red property 'split' of null" upon "user:create" operation. **The user is created, no problem at that part**. Just the return message is indicating some kind of a problem. 
OS - Ubuntu Desktop 20.04.03 (installed on VirtualBox 6.1.32)
sfcc-ci - 2.9.1
node - 14.17.3 (installed with nvm)
![userCreate](https://user-images.githubusercontent.com/90276806/154026541-ab7b37e6-59a8-4af1-9418-28caefaa27ac.jpg)

**Comment by tobiaslohr** [comment]
Thanks for raising! @fy2sysnotify please review https://github.com/SalesforceCommerceCloud/sfcc-ci/pull/296
