### ISSUE TITLE
User creation fails on windows

### ISSUE THREAD

**Issue by JulioFERRANDIS** [SalesforceCommerceCloud/sfcc-ci#300]
After authentification, through windows client, the user creation on account manager fails
the --org parameter seems not to be recognized

D:\Sources\Connecteur SFCC\2.6>sfcc-ci-win user:create --org 'Celine S.A.' --login 'johnny.begoode@celine.fr' --user '{"firstName":"Johnny", "lastName":"BeGoode", "roles": ["bm-user"]}'
Error: Ambiguous options. Pass either -o,--org or -i,--instance.

**Comment by tobiaslohr** [comment]
@JulioFERRANDIS Thanks for raising. We have seen users reporting this issue before. The error is thrown for the case the CLI did not get an org OR an instance passed or if both are passed at the same time. Since you are not passing an instance, I think the CLI does not recognise the org you are passing. Since you are on Windows my first guess is, that the way how parameters are passed into the CLI are different on Windows and e.g. due to the Windows terminal being used. Can you double check, that `--parametername parametervalue` is the way to do that?

**Comment by JulioFERRANDIS** [comment]
Hello
I made the test with cyril Pierron and i saw the issue too
I'm not sure to understand exactly what you expect from me. What do you mean by Can you double check, that --parametername parametervalue is the way to do that?

when i launch a sfcc-ci user:create --help, i'm told that a --org parameter is expected. 
C:\Users\adm-ferrj>sfcc-ci user:create --help
Usage: user:create [options]

Create a new user

Options:
  -o, --org <org>            Org to create the user for
  -i, --instance <instance>  Instance to create the user on. Can be an instance alias.
  -l, --login <login>        Login of the user
  -u, --user <user>          User details as json
  -j, --json                 Formats the output in json
  -h, --help                 output usage information

**Comment by tobiaslohr** [comment]
@JulioFERRANDIS and still the question is, whether on Windows and in the terminal you use, the CLI receives the values. I strongly believe it is not, hence raising that question.

Just to double check:

What is the output you are seeing for `sfcc-ci --version`?

**Comment by JulioFERRANDIS** [comment]
C:\Users\adm-ferrj>sfcc-ci --version
2.9.1

C:\Users\adm-ferrj>

**Comment by tobiaslohr** [comment]
Hi @JulioFERRANDIS, unfortunately not. I personally have no Windows machine here and cannot test (and reproduce) therefore. I can only tell you (as I'm on a Mac) that it works on other OS's terminals, so I was assuming it's something related to the Windows terminal and how it gets arguments and options passed.

**Comment by JulioFERRANDIS** [comment]
Can't you (salesforce) find a windows envirionment ?
what i can tell you si that cli doesn't work for me at all, so it's useless

**Comment by tobiaslohr** [comment]
Sorry to hear that the CLI is useless for you under Windows. I can understand your frustration.

This tool is moderated, managed and evolved by the Salesforce Commerce Cloud community, incl. partners and customers. While there are people from Salesforce (including myself) working on and with the tool, this is not a Salesforce product and there is no guarantee that things work on every OS and in every environment.

However, I'll check in our Community Slack group at https://sfcc-unofficial.slack.com/archives/CAUFG3SHF if there are other people facing the same issue. If you are not a member yet of https://sfcc-unofficial.slack.com, I can only encourage you to join as there are lot's of Community members which may be able to help.

**Comment by tobiaslohr** [comment]
@JulioFERRANDIS I've asked in our community slack on your behalf, see https://sfcc-unofficial.slack.com/archives/CAUFG3SHF/p1655978490438169?thread_ts=1655977614.103509&cid=CAUFG3SHF

> As far as I know in Windows you need to quote parameters with double quotes, so --org "Celine S.A."

Did you try that?

**Comment by matthewrose** [comment]
@JulioFERRANDIS Also you will need to escape the double quotes in the JSON string with a `\` like so `\"`

**Comment by sh-si** [comment]
would be great to get an update here @JulioFERRANDIS

**Comment by JulioFERRANDIS** [comment]
Hello
I could manage it. Thanks a lot for the tips

my remaining issue concerns authentification. I currently need to pass through salesforce  authentificator but as i use a service account it's not possible to use it.
We can close this topic
