### ISSUE TITLE
SLAS commands not available in the latest release 2.9.1

### ISSUE THREAD

**Issue by pavelkukov** [SalesforceCommerceCloud/sfcc-ci#304]
I'm reporting two issues:
1. SLAS commands are not available in version 2.9.1. 
2. Also, a wrong version is reported from the module's `--version` command.
I've installed version 2.9.1 but `sfcc-ci -V` reports 2.6.0
See:

![image](https://user-images.githubusercontent.com/1914217/157602118-729c56cc-099e-4fc9-8e1c-ee48c7d2069e.png)

**Comment by clavery** [comment]
@pavelkukov I think the case here is that you have two versions installed. Your globally installed version is being executed over your npm installed version. 

If you execute `where sfcc-ci` that might give more information on where it's installed. Perhaps you used the prebuilt binary install method originally as documented in the readme. That version may be 2.6.0

**Comment by pavelkukov** [comment]
Thank you @clavery ! Indeed something like that has happened.
I've deleted npm & npm cache and started working correctly. Maybe I had multiple versions due to nvm.
