### ISSUE TITLE
sandbox:create equivalent in Javascript API is missing?

### ISSUE THREAD

**Issue by mhoinaru-gpsw** [SalesforceCommerceCloud/sfcc-ci#305]
I noticed there is a sandbox:create CLI command, but I cannot find the equivalent in the Javascript API.

**Comment by tobiaslohr** [comment]
@mhoinaru-gpsw Thanks for opening. You are right, the JS API does not cover all of the functionalities exposed via the CLI commands. The tool has a primary focus on the CLI and therefore the JS API is secondary and thus does not cover all of the functionalities.
