### ISSUE TITLE
Error on code:deploy with JWT token type

### ISSUE THREAD

**Issue by NicoloMenandroDiana** [SalesforceCommerceCloud/sfcc-ci#323]
Hello,

I've changed my client API from UUID to JWT due to the SalesForce communication regarding the UUID future deprecation.

Once done, all works fine except the code:deploy command that gives me this error:
_Error: WebDAV authentication failed. Please (re-)authenticate first by running ´sfcc-ci auth:login´ or ´sfcc-ci client:auth´. No token auto-renewal is performed. If the problem still occurs please check the WebDAV Client Permissions on the instance and ensure your client ID has been granted access to required WebDAV resources._

Switching back to UUID, all works fine.

Could be a problem with the token length?

Thanks for your help.

Best regards,
NM

**Comment by tobiaslohr** [comment]
Hi @NicoloMenandroDiana, this error is expected and known. Salesforce is working on a solution to this.

The underlying reason for this is, that with certain auth grants (`sfcc-ci auth:login` and `sfcc-ci client:login <client> <secret> <user> <user_password>`) being used to login and obtain the access tokens, commands executed against B2C Commerce instances implemented via OCAPI Data API or WebDAV API will not work, if the API client's token format is set to JWT.

Due to this issue, the CLI commands will fail.

Based on your observation, and until a fix from Salesforce is available, I'd like to ask you to switch the token format of your API client back to UUID.

**Comment by danechitoaie** [comment]
@tobiaslohr is this a Salesforce issue or a SFCC-CI issue?

Switching to JWT seems to be working ok for https://plugins.jenkins.io/osf-builder-suite-for-sfcc-deploy/
And with Postman as well:

1)
```HTTP
POST /dwsso/oauth2/access_token HTTP/1.1
Host: account.demandware.com
Authorization: Basic ????
Content-Type: application/x-www-form-urlencoded
Content-Length: 29

grant_type=client_credentials
```
2)
```HTTP
PUT /on/demandware.servlet/webdav/Sites/Cartridges/version1/test.png HTTP/1.1
Host: ????-???.sandbox.us01.dx.commercecloud.salesforce.com
Authorization: Bearer <JWT_TOKEN_FROM_STEP1_HERE>
Content-Type: image/png
Content-Length: 22

"<file contents here>"
```

**Comment by NicoloMenandroDiana** [comment]
Thank you @tobiaslohr for your help.

I've switched back to UUID format as you suggested.

Best Regards,
NM

**Comment by tobiaslohr** [comment]
Here is also a wiki page which should help to understand this: https://github.com/SalesforceCommerceCloud/sfcc-ci/wiki/Token-format-change-from-UUID-to-JWT

**Comment by AlessioBarbiero-Diana** [comment]
Hi @tobiaslohr, is there any news about this bug? Has it been fixed?
Salesforce has again sent a reminder that the changes will take effect on 15/06/23.

Thank you for your help

**Comment by tobiaslohr** [comment]
Hi @AlessioBarbiero-Diana, if you experience any issues after changing token format from UUID to JWT, there is no other option than switch it back to UUID right now.

**Comment by AlessioBarbiero-Diana** [comment]
Hi @tobiaslohr, thank you for your response. For now, I can keep the UUID format but on 15/06 we will be forced from Salesforce to switch to the JWT token type. Have you got in plan to fix the problem before that date?

Thank you

**Comment by tobiaslohr** [comment]
Hi @AlessioBarbiero-Diana, this is not an issue of the CLI tool itself but an underlying problem of B2C Commerce as it did not fully support token format JWT for all Oauth grant types, only client_credentials was supported. From what I understood, B2C Commerce supports that as of 23.2.

**Comment by AlessioBarbiero-Diana** [comment]
Hi @tobiaslohr, any updates regarding this issue? I'm trying right now but the problem still persists and the deprecation date is in 2 days. I've checked the requirements described in https://github.com/SalesforceCommerceCloud/sfcc-ci/wiki/Token-format-change-from-UUID-to-JWT but the command code:deploy is still not working.

Thank you
