### ISSUE TITLE
auth:renew should respect set alternative AccountManager url

### ISSUE THREAD

**Issue by wundrian** [SalesforceCommerceCloud/sfcc-ci#34]
Currently, `auth:renew` calls `obtainToken` with no AccountManager override. So when one was initially set, `renew` will try to re-authenticate with the standard AccountManager.

**Comment by tobiaslohr** [comment]
@wundrian is this still relevant?

**Comment by wundrian** [comment]
I'll need to retest, but the need hasn't gone away.

**Comment by tobiaslohr** [comment]
@wundrian Do you make use of the env var `SFCC_LOGIN_URL`? This is respected by `obtainToken`. I did a quick test, see below:

```
$ export SFCC_LOGIN_URL=<your-alt-am-host>
$ sfcc-ci client:auth '<client-id>'' '<client-secret>' --renew
Authentication succeeded Auto-renewal enabled.
$ sfcc-ci client:auth:renew
Authentication renewal succeeded
```

Feedback?

**Comment by wundrian** [comment]
Good point. Our invocations go via the `-a <am-host>`, but I think we can work with environment variables.

**Comment by tobiaslohr** [comment]
I think respecting the alternative Account Manager host passed to `sfcc-ci client:auth` via `-a` flag, is not trivial. The setting is only visible to the current Node process running the command, this includes playing with `process.env.SFCC_LOGIN_URL` and setting the host. One option would be to persist the setting into the CLIs local configuration. That however, has the downside that it would be visible across shells and sessions.

I'd personally favor to deprecate the flag `-a` for command `sfcc-ci client:auth` and rely on env var `SFCC_LOGIN_URL`.

**Comment by tobiaslohr** [comment]
I've created #129 for the removal of flag `-a,--authserver` and closing this one.
