### ISSUE TITLE
sfcc-ci auth:login sending approval request to Authenticator

### ISSUE THREAD

**Issue by Randhir-Matkar** [SalesforceCommerceCloud/sfcc-ci#354]
### sfcc-ci Version

2.11.0

### NodeJS Version

12.19.0

### sfcc-ci Path

/usr/local/bin/sfcc-ci

### Host OS Details

Linux 403160fb-42ac-4f15-8087-ce1fd2751282-wbc5r 5.15.0-1028-aws #32~20.04.1-Ubuntu SMP Mon Jan 9 18:02:08 UTC 2023 x86_64 GNU/Linux

### What happened?

We have setup of sfcc-ci for automation use cases in CI/CD pipeline, when the pipeline triggers at auth:login command it sends pop-up to approve the login request in Salesforce Authenticator.

Can u suggest the Best way to use cases for sfcc-ci tool to avoid the 2 MFA auth everytime login into the commerce cloud.

### Relevant log output

```shell
sfcc-ci client:auth $SFCC_OAUTH_CLIENT_ID $SFCC_OAUTH_CLIENT_SECRET -r
Error: Authentication failed: null
```

**Comment by tobiaslohr** [comment]
Hi @Randhir-Matkar, note there is a difference in the commands `sfcc-ci auth:login` and `sfcc-ci client:auth`.

`sfcc-ci client:auth` should be used with only client credentials and thus is not authenticating a user who is bound to 2FA. However, the `sfcc-ci client:auth` applies fallbacks to attempt to look for user credentials in e.g. a `.env` file or a `dw.json`, so I suggest you run it with the `-D` flag to watch out which auth flow (with or without user) it is using.

**Comment by Randhir-Matkar** [comment]
Thanks @tobiaslohr  for pointing out the root cause changes. Now we are able to use the sfcc-ci for automation purpose.
