### ISSUE TITLE
How to run locally 

### ISSUE THREAD

**Issue by rajiv-sachdeva** [SalesforceCommerceCloud/sfcc-ci#83]
Using source code if I don't want to install sfcc-ci globally and run it locally using npm run sfcc-ci how do I do that ? It says sfcc-ci doesn't exists !

**Comment by tobiaslohr** [comment]
@rajiv-sachdeva can we close this issue?

**Comment by mittinti** [comment]
@tobiaslohr , the windows installer is not working neither the mac one. The steps are really confusing how to use this extension. Can you please elaborate more on the installation steps.

Ex :
1. when I run the .exe in windows it auto closes
2. In mac the installer cannot be installed as it say its not from trusted sources related error.

**Comment by tobiaslohr** [comment]
@mittinti the windows binary is not an installer, but an executable for use at the command line. running that executable from the desktop does not make any sense. the mac executable is not using an Apple Developer ID signature, hence the warning for the installer on a mac

**Comment by mittinti** [comment]
Sir, I know this is community service and free of cost.  But can you please make these statements in documentation clearly. I never understood these facts until you tell them out, made no sense to me.

Thanks for the reply and understanding

**Comment by tobiaslohr** [comment]
@mittinti what exactly is not clear? Aren't the steps described in the readme not sufficient. If not, please let us know which ones.

**Comment by mittinti** [comment]
The current README file for windows has only 2 steps. I have executed those steps and did not work for me. I have switched to node version which worked for me.

**Comment by tobiaslohr** [comment]
>The current README file for windows has only 2 steps. I have executed those steps and did not work for me. I have switched to node version which worked for me.

@mittinti  I'm not a Windows expert. Do you want to share any error message or suggestion on additional steps if required? Then we can adjust the readme. Or - even better - you submit a PR with the steps needed from your point of view. Thanks much!
