### ISSUE TITLE
Add client secret encoding for client authentication

### ISSUE THREAD

**Issue by tobiaslohr** [SalesforceCommerceCloud/sfcc-ci#97]
With Account Manager deployments on Mon Feb 24th a breaking change has been introduced which may block API clients not being able to authenticate as the client secret may include non URL safe characters.

~~Proposal is to add a new env var `SFCC_AUTH_ENCODE_SECRET`. If set to `true` or `1` the client secret used for authentication will be url encoded before base64 encoding.~~

We will apply url encoding of the client secret used for authentication before base64 encoding.

**Comment by wundrian** [comment]
Looks like AM reverted their change, at least I can authenticate with my special characters password via curl but not via sfcc-ci.

**Comment by tobiaslohr** [comment]
@wundrian I can still run an auth with API client credentials containing special non-URL safe characters in the secret
